apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
    spec:
      containers: 
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hiii; sleep 5; done"]
      