apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoexpress.name}}
  labels:
    app: {{ .Values.mongoexpress.label}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongoexpress.label}}
  replicas: {{ .Values.mongoexpress.replicaCount}}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoexpress.label}}
    spec:
      containers:
      - name: {{ .Values.mongoexpress.containerName}}
        image: {{ .Values.mongoexpress.image}}
        ports:
        - containerPort: {{ .Values.mongoexpress.containerPort}}

        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.secret}}
              key: {{ .Values.mongodb.username}}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.secret}}
              key: {{ .Values.mongodb.password}}
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name}}
              key: {{ .Values.configMap.databaseUrl}}