kind: Deployment
apiVersion: apps/v1
metadata:
   name: {{ .Values.name}}
spec:
    {{- if .Values.replica}}
   replicas: {{ .Values.replicaCount}}
    {{- end}} 
   selector:      
    matchLabels:
     name: {{ .Values.label}}
   template:
     metadata:
       name: {{ .Values.podName}}
       labels:
         name: {{ .Values.label}}
     spec:
      containers:
          {{- with .Values.containerInfo}}
        - name: {{ .containerName }}
          image: {{ .imageName }}
          ports:
            - containerPort: {{ .port}}
          {{- end}}