
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-auto-scalar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.hpa_name}}
  minReplicas: {{ .Values.minReplicas}}
  maxReplicas: {{ .Values.maxReplicas}}
  metrics: 
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.CPU_Utilization}}
    


