kind: Pod                              
apiVersion: v1                     
metadata:                            
  name: {{ .Values.name}}                  
spec:                                     
  containers:   
  {{- toYaml .Values.containers | nindent 4}}                     
    